### ISSUE TITLE
Generate playbook to reset password

### ISSUE THREAD

**Issue by kevinmichaelchen** [TeslaGov/gradle-ansible-plugin#1]
Example playbook should be named `rampart_passsword-reset.yml` if we're resetting the `rampart` user's password. Playbook should look like:
```yml
- hosts: lin-pluto.neapix.bae.net
  remote_user: rampart
  become: yes
  vars:
    ansible_password: '{{ rampart_password }}'
    ansible_become_pass: '{{ rampart_password }}'
  tasks:
    - name: Reset password
      shell: chage -d 0 rampart; echo 'rampart:{{ new_password }}' | chpasswd
```

The reset task needs to take in arguments for the hosts, the user, and the user's password.
